version: '3'
services:
  filebeat:
    image: elastic/filebeat:7.7.0
    restart: unless-stopped
    command: filebeat -e -strict.perms=false
    volumes:
      - ./Filebeat/config.yml:/usr/share/filebeat/filebeat.yml
      - ./Filebeat/test_log.log:/logs/test_log.log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - elk
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:7.7.0
    container_name: elk-elasticsearch
    volumes:
      - ./ELK/elasticsearch/config.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    networks:
      - elk
    ports:
      - "9200:9200"

  logstash:
    image: logstash:7.7.0
    container_name: elk-logstash
    volumes:
      - ./ELK/logstash/config.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./ELK/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.7.0
    depends_on:
      - elasticsearch
    volumes:
      - ./ELK/kibana/config.yml:/usr/share/kibana/config/kibana.yml:ro
    networks:
      - elk
    ports:
      - "5601:5601"

networks:
  elk:
    driver: bridge